apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/seojointly/SesacM.git'
    targetRevision: main
    path: k8s/helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true