dependencies {
  // common-proto
  implementation project(':common-proto')
  
  // Spring Web
  implementation 'org.springframework.boot:spring-boot-starter-webmvc'
  
  // Spring Actuator
  implementation 'org.springframework.boot:spring-boot-starter-actuator'

  // Spring Cloud Starter Eureka Client
  implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
  
  // Spring Cloud Starter OpenFeign
  implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
  
  // gRPC Client
  implementation 'net.devh:grpc-client-spring-boot-starter:3.1.0.RELEASE'
}