apiVersion: v1
kind: Service
metadata:
  name: portal-service
spec:
  type: NodePort
  selector:
    app: portal-service
  ports:
    - port: 80          # 내부 클러스터 통신용(중간 포트로 아무 포트나 가능하지만 웹은 80 추천)
      targetPort: 8080  # 파드 포트(컨테이너 포트, 스프링 부트 포트와 일치)
      nodePort: 30080   # 브라우저에서 http://localhost:30080 으로 접속