dependencies {
  // WebMVC, Actuator
  implementation 'org.springframework.boot:spring-boot-starter-webmvc'
  implementation 'org.springframework.boot:spring-boot-starter-actuator'

  // AOP & AspectJ 의존성 명시 (TimedAspect 구동을 위함)
  // implementation 'org.springframework.boot:spring-boot-starter-aop'
  // - 원래는 이 디펜던시(스타터)를 사용해야 하나, 2026-09월 기준 BOM 설정이 누락되어 있는 것으로 보임 (언젠가는 되겠죠)
  // - 아래 두 디펜던시는 spring-boot-starter-aop에 포함된 디펜던시임
  implementation 'org.springframework:spring-aop'
  implementation 'org.aspectj:aspectjweaver'
  
  // 1. Metrics (Prometheus)
  implementation 'io.micrometer:micrometer-registry-prometheus'

  // 2. Tracing (OpenTelemetry Bridge + Zipkin Exporter)
  implementation 'io.micrometer:micrometer-tracing-bridge-otel'
  implementation 'io.opentelemetry:opentelemetry-exporter-zipkin'

  // 3. Logging (Loki4j Logback Appender)
  implementation 'com.github.loki4j:loki-logback-appender:1.5.1'
}