apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-db-credentials-sync
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: db-secret 
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: prod/app/db-credentials-5
        property: DB_USERNAME  
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/app/db-credentials-5
        property: DB_PASSWORD