apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-secret-credentials
            key: secret-access-key