apiVersion: v1
kind: ConfigMap
metadata:
  name: message-config  # application.yml의 spring.cloud.kubernetes.config.name과 일치!
  namespace: default
data:
  # application.yml 형식으로 설정 내용을 작성
  application.yml: |
    message:
      greeting: "Hello, K8s Native!"  # 이 값을 수정하고 apply 하면 반영됨