dependencies {
  // Spring Cloud Starter Config (Client)
  implementation 'org.springframework.cloud:spring-cloud-starter-config'
  
  // Spring Cloud Starter Netflix Eureka Client
  implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

  // Spring Starter Web
  implementation 'org.springframework.boot:spring-boot-starter-web'
}