server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msa_user_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  server-url: http://localhost:8080
  # Keycloak 전체를 제어할 수 있는 Admin 토큰 발급 (인증 주체)
  realm: master        # 기본 정보, admin tocken 발급받을 때 사용
  client-id: admin-cli # 기본 정보, admin tocken 발급받을 때 사용
  username: admin
  password: 1234
  # 유저 계정이 실질적으로 저장될 비즈니스 렐름 (작업 대상)
  target-realm: msa-shop