apiVersion:  v1
kind: Pod
metadata: 
  name: multi-pod
spec: 
  containers:
    - name: web
      image: nginx:alpine
      volumeMounts:
        - name: shared
          mountPath: /shared

    - name: logger
      image: busybox
      command:
        - sh
        - -c
        - |
          while true; do
            date >> /shared/date.log
            sleep 5
          done
      volumeMounts:
        - name: shared
          mountPath: /shared

  volumes:
    - name: shared
      emptyDir: {}