plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
    // AWS SDK v2 BOM (버전 관리 통합)
    implementation platform('software.amazon.awssdk:bom:2.54.13')

    // AWS 서비스 클라이언트 디펜던시 (BOM을 따르므로 버전 생략)
    implementation 'software.amazon.awssdk:dynamodb-enhanced'
    implementation 'software.amazon.awssdk:ses'                  // 추가: AWS SES
    implementation 'software.amazon.awssdk:pinpointsmsvoicev2'   // 추가: AWS Pinpoint SMS Voice V2

    // Spring Boot & Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    
    // Lombok 설정
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    
    // Test 설정
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}
