server:
  port: 8081

spring:
  application:
    name: order-service

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/msa_order_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    function:
      # 수신 함수 구분자: 세미콜론(;)
      definition: stockSuccess;stockFailure

    stream:
      bindings:
        # 주문 생성
        orderCreated-out-0:
          destination: order-created-topic
          content-type: application/json

        # 재고 차감 성공 수신
        stockSuccess-in-0:
          destination: stock-success-topic # topic name
          group: order-stock-success-group # group name (실패와 동일한 그룹으로 줘도 됨)
          consumer:
            max-attempts: 3

        # 채고 차감 실패 수신
        stockFailure-in-0:
          destination: stock-failure-topic # topic name
          group: order-stock-failure-group # group name
          consumer:
            max-attempts: 3

      rabbit:
        bindings:
          orderCreated-out-0:
            producer:
              routing-key-expression: "'order.created'"
          stockSuccess-in-0:
          # dlq 활성화 조건
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
          stockFailure-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true