server:
  port: 8082

spring:
  application:
    name: stock-service
  
  # Java 21 가상 스레드 활성화 (메시지 수신 및 I/O 블로킹 구간에서 처리량 극대화)
  threads:
    virtual:
      enabled: true
  
  # 스프링 컨테이너에 등록된 Consumer 빈(@Bean Consumer<...>)의 이름을 수신 함수로 등록
  cloud:
    function:
      definition: stockControl # consumer bean name
      
    stream:
      bindings:
        # 입력 채널 명명 규칙: <함수명>-in-<인덱스>
        # stockControl 함수의 0번 입력 파이프라인 설정
        stockControl-in-0:
        
          # RabbitMQ의 Exchange 이름 (Producer가 메시지를 보낸 Exchange 명칭과 반드시 일치해야 함)
          destination: order-created-topic
          
          # 컨슈머 그룹 지정
          # 1) RabbitMQ에 'order-events.stock-group' 이름의 물리적 큐가 생성됨
          # 2) 동일 그룹 내 인스턴스가 여러 대 떠도 메시지는 한 곳에만 전달되어 중복 처리를 방지(경쟁 소비자 패턴)
          group: stock-group
          
          consumer:
            # 메시지 소비 실패 시 인메모리 최대 재시도 횟수 (기본 1회 시도 + 추가 재시도 2회 = 총 3회)
            max-attempts: 3
            
      rabbit:
        bindings:
          stockControl-in-0:
            consumer:
              bindingRoutingKey: 'order.*'
              autoBindDlq: true
              republishToDlq: true