# ~/k8s/deployment/nginx-rollup.yaml
# deployment\nginx-rollup.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rollup
  annotations:
    kubernetes.io/change-cause: "Deploy nginx version 1.21" # Rollout History 기록용
spec:
  replicas: 3
  revisionHistoryLimit: 5  # 보관할 이전 ReplicaSet 히스토리 최대 수량 (기본값: 10)
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # 배포 중 Desired Replicas 대비 초과 생성 허용 수량 (최대 3+1=4개)
      maxUnavailable: 1  # 배포 중 순간적으로 다운 타임을 허용하는 최대 수량 (최소 3-1=2개 유지)
  selector:
    matchLabels:
      app: nginx-rollup
  template:
    metadata:
      labels:
        app: nginx-rollup
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80