plugins {
  id 'java'
  id 'com.gradleup.shadow' version '9.6.1'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

repositories {
  mavenCentral() 
}

dependencies {
  implementation 'com.amazonaws:aws-lambda-java-core:1.4.0'
  implementation 'com.amazonaws:aws-lambda-java-events:3.16.1'
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}

tasks.named('shadowJar') {
  archiveClassifier.set('')
}

tasks.named('build') {
  dependsOn tasks.named('shadowJar')
}